name: smart_mutation_example
description: An example project demonstrating mathematical operations for mutation testing

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0

dependencies:
  # No external dependencies needed for this example
